# Generated by Django 3.1.1 on 2020-11-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201119_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
