# Generated by Django 3.1.1 on 2020-11-20 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20201119_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentdepartment', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('incidentlocation', models.CharField(max_length=50)),
                ('initialserverity', models.CharField(max_length=70)),
                ('ImmediateAcitonTaken', models.CharField(max_length=80)),
                ('SubIncident', models.CharField(max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
